version: '3.7'

services:
  vue:
    container_name: dj_react_frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080